### ISSUE TITLE
Bot not working :(

### ISSUE THREAD

**Issue by ghost** [uzarnom/BitBucket-to-Discord-commit-bot#1]
When i run the bot with everything configured i get this error
![image](https://user-images.githubusercontent.com/28850156/34342544-73f1076c-e981-11e7-8a6d-c49850c41c78.png)

**Comment by uzarnom** [comment]
oh god i didn't expect anyone to ever use this, give me some time to relearn what i'm doing

**Comment by uzarnom** [comment]
All fixed, sorry for the trouble. grab a new copy and should be all good
